.nh
.TH SSRT   2022-06-14 budlabs "User Manuals"
.SH NAME
.PP
ssrt - simplescreenreocrder - now even simpler

.SH USAGE
.PP
ssrt [OPTIONS]

.PP
\fIevent scripts\fP are stored in
\fBSSR_CONFIG_DIR\fP/events* ,
as executable files with the same name as the
event (delay|pause|resume|start|stop).
When \fBssrt\fP is launched for the first time a sample
\fB\fCevents\fR directory will be created but
the scripts are \fI"empty"\fP\&.

.PP
.RS

.PP
* SSR_CONFIG_DIR defaults to simplescreenrecorders
configuration directory: \fB\fC~/.ssr\fR

.RE

.SH OPTIONS
.PP
.RS

.nf
-e, --codec      CODEC     | CODEC defaults to h264 (or vp8 for webm).  
-c, --config-dir DIR       | set ssr conifg directory
-n, --container  CONTAINER | set CONTAINER type. example containers: mkv and webm.  
-d, --delay      SECONDS   | delay start of recording
-h, --help                 | print help and exit  
-i, --input-file FILE      | change default (/tmp/ssrt/in) inputfile. 
-m, --mute                 | disables audio in recording  
-p, --pause                | toggle play/pause or start a new recording.  
-s, --select               | select recording area before recording starts.
-v, --version              | print version info and exit  

.fi
.RE

.SS -c, --config-dir DIR
.PP
Defaults to \fB\fC~/.ssr\fR .
This option overrides the environment-variable
\fBSSR_CONFIG_DIR\fP\&.

.SS -d, --delay      SECONDS
.PP
This option has no effect when stopping or toggling
play/pause. When it do have effect it will also
trigger the \fBdelay event\fP and pass SECONDS as
the first argument to the delay event script.

.SS -i, --input-file FILE
.PP
Commands can be sent to this file while the recording.
Below are whats listed in \fB\fCsimplescreenrecorder(1)\fR:

.PP
.RS

.nf
  record-start          Start the recording.
  record-pause          Pause the recording.
  record-cancel         Cancel the recording and delete the output file.
  record-save           Finish the recording and save the output file.
  schedule-activate     Activate the recording schedule.
  schedule-deactivate   Deactivate the recording schedule.
  window-show           Show the application window.
  window-hide           Hide the application window.
  quit                  Quit the application.

.fi
.RE

.PP
To send a command simple echo it to the input-file:
.br
\fB\fCecho record-pause > /tmp/ssrt/in\fR

.PP
This option overrides the environment
variable \fBSSRT_INPUT_FILE\fP\&.

.SS -s, --select
.PP
This option executes \fB\fCslop(1)\fR . Without this option
the full active monitor will be recorded.

.SH CONTACT
.PP
Send bugs and feature requests to:
.br
https://github.com/budlabs/ssrt/issues

.SH COPYRIGHT
.PP
Copyright (c) 2020-2022, budRich of budlabs
.br
SPDX-License-Identifier: BSD-2-Clause

.SH CONTACT
.PP
File bugs and feature requests at the following URL:
.br
https://github.com/budlabs/ssrt/issues

.SH COPYRIGHT