.\" -*- mode: troff; coding: utf-8 -*-
.TH "ssrt" "1" "2022-04-01" "" ""
.SH
ssrt
.LP
short description of the script
.LP
\l'2i'
.LP
usage: ssrt [OPTIONS]
.LP
.EX
-o, --hello WORD | short description          
-v, --version    | print version info and exit
-h, --help       | print help and exit        
.EE
.SH
USAGE
.LP
This is just a boilerplate.  \fBbold\fR \fIitalic\fR
and other \fCmarkdown\fR options are supported.  
.PP
dependencies:
.br
- make, bash, gawk
.br
- \fClowdown\fR , for markdown conversion  
.IP "\[u2611]" 2
easy peasy
.br
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\[u2610]" 2
\fBmake\fR it your own
.SH
OPTIONS
.SS
\fC-o\fR, \fC--hello\fR   WORD
.LP
\fC--hello\fR long description
.br
this is the long description for \fC--hello\fR
.br
first line in \fC./docs/hello\fR is the short description.
.SH
SEE ALSO
.LP
Project site: 
.SH
CONTACT
.LP
File bugs and feature requests at the following URL:
.br
.SH
AUTHOR
.LP
ssrt was written by  of 
