.nh
.TH SSRT  1 2022-04-04 budlabs "User Manuals"
.SH NAME
.PP
ssrt - simplescreenreocrder - now even simpler

.SH USAGE
.PP
ssrt [OPTIONS]

.PP
\fIevent scripts\fP are stored in
\fBSSR_CONFIG_DIR\fP/events* ,
as executable files with the same name as the
event (delay|pause|resume|start|stop).
When \fBssrt\fP is launched for the first time a sample
\fB\fCevents\fR directory will be created but
the scripts are \fI"empty"\fP\&.

.PP
.RS

.PP
* SSR_CONFIG_DIR defaults to simplescreenrecorders
configuration directory: \fB\fC~/.ssr\fR

.RE

.SH OPTIONS
.PP
.RS

.nf
-h, --help     | print help and exit  
-v, --version  | print version info and exit  

.fi
.RE

.SH CONTACT
.PP
Send bugs and feature requests to:
.br
https://github.com/budlabs/ssrt/issues

.SH COPYRIGHT
.PP
Copyright (c) 2020-2022, budRich of budlabs
.br
SPDX-License-Identifier: BSD-2-Clause

.SH CONTACT
.PP
File bugs and feature requests at the following URL:
.br
https://github.com/budlabs/ssrt/issues

.SH COPYRIGHT