#!/usr/bin/env bash

# this event gets triggered when ssrt a new recording
# starts.
# the event is actually triggered just before the recording
# starts, hence the event varialbe $SSR_OUTPUTFILE 
# is empty here.
