#!/usr/bin/env bash

### this file and the createconf() function is
### automatically generated by bashbud based on
### the content of the conf/ directory

createconf() {
local trgdir="$1"
declare -a aconfdirs

aconfdirs=(
"$trgdir/events"
)

mkdir -p "$1" "${aconfdirs[@]}"

cat << 'EOCONF' > "$trgdir/events/delay"
#!/bin/bash

# this event is triggered before recording starts
# if --delay options is used. If there exist no
# executable file: events/delay
# a silent sleep will be used

# the argument passed to --delay is available as
# $1 in this file.
declare -i del=$1 
declare -i _dunstid=1338

if ifcmd dunstify ; then
  while ((del--)); do
    dunstify -r "$_dunstid" "recording starts in $((del+1))"
    sleep 1
  done
  
  dunstify --close "$_dunstid"
elif ifcmd notify-send ; then
  notify-send --expire-time "$del" \
    "recording delayed $del seconds."
  sleep "${del}"
else
  sleep "${del}"
fi
EOCONF

chmod +x "$trgdir/events/delay"
cat << 'EOCONF' > "$trgdir/events/stop"
#!/bin/bash

opf=$SSR_OUTPUTFILE
notify-send "i stopped $opf"

EOCONF

chmod +x "$trgdir/events/stop"
cat << 'EOCONF' > "$trgdir/events/resume"
#!/bin/bash

echo i resumed
EOCONF

chmod +x "$trgdir/events/resume"
cat << 'EOCONF' > "$trgdir/events/start"
#!/bin/bash

notify-send "im starting"
EOCONF

chmod +x "$trgdir/events/start"
cat << 'EOCONF' > "$trgdir/events/pause"
#!/bin/bash

echo i paused
EOCONF

chmod +x "$trgdir/events/pause"
}
