#!/bin/bash

declare -i del=$1 _dunstid=1338

if ifcmd polify ; then
  while ((del--)); do
    polify --module timer \
      "recording starts in $((del+1))"
    sleep 1
  done
elif ifcmd dunstify ; then
  while ((del--)); do
    dunstify -r "$_dunstid" "recording starts in $((del+1))"
    sleep 1
  done
  
  dunstify --close "$_dunstid"
elif ifcmd notify-send ; then
  notify-send --expire-time "$del" \
    "recording delayed $del seconds."
  sleep "${del}"
else
  sleep "${del}"
fi
