#!/bin/bash

f=$1

tmpdir=/tmp/ssrt-postprod
mkdir -p "$tmpdir"
if=$tmpdir/in
of=$tmpdir/out.mkv
audio=$tmpdir/a.ogg

cp "$f" "$if"

polify --module timer "extracticting audio..."
ffmpeg -i "$if" -vn -acodec copy "$audio"
polify --module timer "save audio as $audio"

(
  cd "$tmpdir" || exit 1
  audacity "$audio"
)

[[ -f $audio ]] && {
  polify --module timer "adding new audio track..."
  ffmpeg -i "$if" -i "$audio" -c:v copy -map 0:v:0 -map 1:a:0 "$of"
}

polify --module timer --clear

[[ -f $of ]] && mv -f "$of" "$f"
rm -rf "$tmpdir"
