#!/bin/bash

_defaultname=testdef
_timeformat='%y%m%d-%H:%M:%S'
_savedir=

[[ -z $_savedir ]] && _savedir=~ \
  && ifcmd xdg-user-dir          \
  && _savedir=$(xdg-user-dir VIDEOS)


f=$1
declare -i validpath

until ((validpath)); do

  path=$(menu -p "Save as: " -f "${_savedir/~/'~'}")
  path=${path/'~'/~}

  [[ -z $path ]] && {
    confirm=$(menu -p "Delete $f ? " No Yes)
    [[ $confirm = Yes ]] && exit
  }

  [[ ${path} =~ ^/ ]] && validpath=1
done

[[ -d $path ]] && {
  path+=/$_defaultname
  [[ -n $_timeformat ]] && path+=$(date +"$_timeformat")
}

# remove file extension entered by user
[[ $path =~ .+[^/.]+[.][a-zA-Z]+$ ]] && path=${path%.*}

# append same extension as the recorded file
[[ $f =~ .*[.][a-zA-Z]+$ ]] && path+=".${f##*.}"

mkdir -p "${path%/*}"

# if target file already exist create a unique
# filename file1.file2...
while [[ -f $path ]]; do
  path="${path%.*}$((++i)).${f##*.}"
done

mv "$f" "$path"
